# -*- coding: utf-8 -*-
"""Tugas 2_Jaya University.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCBjKQZIIspSmaYGyHOQDszIxyR7dpAN
"""

!pip install shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# Model
import lightgbm as lgb
from lightgbm import LGBMClassifier

# Evaluasi
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from scipy.stats import randint, uniform

# Imblearn pipeline akan menangani oversampling DENGAN BENAR
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler

# ColumnTransformer untuk menerapkan preprocessing yang berbeda ke kolom berbeda
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

"""#Import Data"""

#Clone repository dari github untuk mengakses dataset yang telah diunggah di github sebelumnya
!git clone https://github.com/Andishafira/Dicoding.git

import pandas as pd

df = pd.read_csv("/content/Dicoding/Belajar Penerapan Data Science/Tugas 2_Menyelesaikan Permasalahan Institusi Pendidikan/data.csv", sep=";")
df.head(100)

"""# Data Understanding"""

df.info()

df.describe(include='all').T

if 'df' in locals():
    print("ANALISIS VARIABEL TARGET (Status)")

    target_col = 'Status'

    # Menghitung jumlah unik dari variabel target
    print(f"\n[ Distribusi Nilai pada Kolom '{target_col}' ]")
    status_counts = df[target_col].value_counts()
    print(status_counts)

    # Menghitung persentase
    print(f"\n[ Persentase Distribusi Kolom '{target_col}' ]")
    status_percentage = df[target_col].value_counts(normalize=True) * 100
    print(status_percentage)

    # Visualisasi distribusi variabel target
    plt.figure(figsize=(8, 5))
    sns.countplot(x=target_col, data=df, order=status_counts.index, palette='viridis')
    plt.title('Distribusi Variabel Target (Status)', fontsize=16)
    plt.xlabel('Status Mahasiswa', fontsize=12)
    plt.ylabel('Jumlah', fontsize=12)

    # Menambahkan label persentase di atas bar
    for i, count in enumerate(status_counts):
        percentage = status_percentage.iloc[i]
        plt.text(i, count + 50, f'{percentage:.1f}%', ha='center', fontsize=11)

    plt.show()
    print("Plot di atas menunjukkan bahwa data kita tidak seimbang (imbalanced).")
    print("Jumlah 'Graduate' paling banyak, diikuti 'Dropout', dan 'Enrolled'.")

if 'df' in locals():
    print("ANALISIS FITUR (CONTOH)")

    # --- Contoh 1: Fitur Numerik (Age_at_enrollment) ---
    print("\n[ Analisis Fitur: Age_at_enrollment ]")
    plt.figure(figsize=(10, 6))
    sns.histplot(df['Age_at_enrollment'], kde=True, bins=30)
    plt.title('Distribusi Umur Saat Mendaftar (Age_at_enrollment)', fontsize=16)
    plt.xlabel('Umur', fontsize=12)
    plt.ylabel('Frekuensi', fontsize=12)
    plt.show()
    print(f"Umur rata-rata: {df['Age_at_enrollment'].mean():.2f}")
    print(f"Umur median: {df['Age_at_enrollment'].median()}")

    # --- Contoh 2: Fitur Kategorikal (Gender) ---
    # Mengganti nilai 0 dan 1 agar lebih mudah dibaca di plot
    df_plot = df.copy()
    df_plot['Gender_label'] = df_plot['Gender'].map({1: 'Laki-laki', 0: 'Perempuan'})

    print("\n[ Analisis Fitur: Gender ]")
    plt.figure(figsize=(7, 5))
    sns.countplot(x='Gender_label', data=df_plot, palette='pastel')
    plt.title('Distribusi Gender', fontsize=16)
    plt.xlabel('Gender', fontsize=12)
    plt.ylabel('Jumlah', fontsize=12)
    plt.show()
    print(df_plot['Gender_label'].value_counts(normalize=True) * 100)

if 'df' in locals():
    print("6. ANALISIS BIVARIAT (FITUR vs TARGET)")

    # --- Contoh 1: Admission_grade vs Status ---
    print("\n[ Hubungan: Admission_grade vs Status ]")
    plt.figure(figsize=(12, 7))
    sns.boxplot(x=target_col, y='Admission_grade', data=df, palette='coolwarm')
    plt.title('Perbandingan Nilai Masuk (Admission Grade) vs Status', fontsize=16)
    plt.xlabel('Status', fontsize=12)
    plt.ylabel('Nilai Masuk', fontsize=12)
    plt.show()
    print("Plot ini membantu melihat apakah ada perbedaan nilai masuk yang signifikan antara ketiga status.")

    # --- Contoh 2: Gender vs Status ---
    print("\n[ Hubungan: Gender vs Status ]")
    plt.figure(figsize=(10, 6))
    sns.countplot(x=target_col, hue='Gender_label', data=df_plot, palette='muted')
    plt.title('Distribusi Status Berdasarkan Gender', fontsize=16)
    plt.xlabel('Status', fontsize=12)
    plt.ylabel('Jumlah', fontsize=12)
    plt.legend(title='Gender')
    plt.show()
    print("Plot ini menunjukkan proporsi laki-laki/perempuan untuk setiap status.")

    # --- Contoh 3: Curricular_units_1st_sem_approved vs Status ---
    print("\n[ Hubungan: Mata Kuliah Lulus Semester 1 vs Status ]")
    plt.figure(figsize=(12, 7))
    sns.boxplot(x=target_col, y='Curricular_units_1st_sem_approved', data=df, palette='Set2')
    plt.title('Mata Kuliah Lulus (Sem 1) vs Status', fontsize=16)
    plt.xlabel('Status', fontsize=12)
    plt.ylabel('Jumlah Mata Kuliah Lulus (Sem 1)', fontsize=12)
    plt.show()
    print("Fitur ini terlihat sangat prediktif. Rata-rata 'Dropout' memiliki jumlah matkul lulus yang jauh lebih rendah.")

if 'df' in locals():
    print("7. HEATMAP KORELASI (ANTAR FITUR NUMERIK)")

    # Menghitung korelasi
    corr_matrix = df.corr(numeric_only=True)

    # Membuat heatmap
    plt.figure(figsize=(20, 16))
    sns.heatmap(corr_matrix, annot=True, fmt='.1f', cmap='coolwarm_r', annot_kws={"size": 8})
    plt.title('Heatmap Korelasi Antar Fitur Numerik', fontsize=20)
    plt.show()

    print("Heatmap ini berguna untuk:")
    print("1. Melihat fitur mana yang berkorelasi kuat satu sama lain (potensi multikolinearitas).")
    print("   Contoh: 'Curricular_units_1st_sem_approved' dan 'Curricular_units_1st_sem_grade' memiliki korelasi tinggi.")
    print("2. (Setelah encoding) Melihat fitur mana yang berkorelasi kuat dengan variabel target.")

"""# Data Preprocessing"""

#hapus baris dengan status= Enrolled
df = df[df['Status'] != 'Enrolled']

# 2. Encode target
df['Status'] = df['Status'].map({'Graduate': 0, 'Dropout': 1})
print("Target 'Status' telah di-encode: Dropout=1, Graduate=0")

X = df.drop(columns=['Status'])
y = df['Status']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Data dibagi menjadi: {X_train.shape[0]} train dan {X_test.shape[0]} test.")

numeric_features = [
    'Age_at_enrollment', 'Curricular_units_1st_sem_approved',
    'Curricular_units_1st_sem_grade', 'Curricular_units_2nd_sem_approved',
    'Curricular_units_2nd_sem_grade'
]

categorical_features = [
    'Application_mode', 'Debtor', 'Tuition_fees_up_to_date',
    'Gender', 'Scholarship_holder'
]

# 1. Buat pipeline untuk preprocessor numerik
numeric_transformer = MinMaxScaler()

# 2. Buat pipeline untuk preprocessor kategorikal
#    Menggunakan OneHotEncoder karena ada fitur seperti 'Application_mode'
#    handle_unknown='ignore' untuk menangani nilai yang mungkin ada di data tes tapi tidak ada di data latih.
categorical_transformer = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# 3. Gabungkan preprocessor menggunakan ColumnTransformer
#    'remainder='passthrough'' berarti kolom yang tidak disebutkan akan dilewatkan apa adanya. Ganti ke 'drop' jika hanya ingin menggunakan fitur yang ada di 'used_cols'.
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='drop' # Kita drop fitur lain yang tidak ada di list Anda
)

pipeline_rf = ImbPipeline(steps=[
    ('preprocessor', preprocessor),
    ('oversampler', RandomOverSampler(random_state=42)),
    ('model', RandomForestClassifier(random_state=123))
])

param_grid_rf = {
    'model__n_estimators': [200, 500],
    'model__max_features': ['sqrt', 'log2'], # 'auto' sudah deprecated
    'model__max_depth' : [6, 8],
    'model__criterion' :['gini', 'entropy']
}

CV_rdf = GridSearchCV(
    estimator=pipeline_rf,
    param_grid=param_grid_rf,
    cv=5,
    n_jobs=-1,
    scoring='accuracy' # Anda bisa ganti ke 'f1' atau 'roc_auc' untuk data imbalanced
)

print("Memulai GridSearchCV untuk Random Forest...")
# Fit pada data latih ASLI. Pipeline akan menangani sisanya.
CV_rdf.fit(X_train, y_train)

print(f"Best parameters ditemukan: {CV_rdf.best_params_}")

# Dapatkan model terbaik dari GridSearch
best_rf_model = CV_rdf.best_estimator_

# Evaluasi pada X_test MURNI (yang belum pernah terlihat)
y_pred = best_rf_model.predict(X_test)

# Dapatkan model terbaik dari GridSearch
best_rf_model = CV_rdf.best_estimator_

# Evaluasi pada X_test MURNI (yang belum pernah terlihat)
y_pred = best_rf_model.predict(X_test)

# --- PERBAIKAN KUNCI #5 ---
# Kita tidak perlu LabelEncoder lagi untuk y_test (Sel #43 & #58)
# y_test kita sudah 0 dan 1.
print("\n--- EVALUASI MODEL TERBAIK PADA DATA UJI ---")
print(f"Akurasi: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Graduate (0)', 'Dropout (1)']))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=['Graduate (0)', 'Dropout (1)'],
            yticklabels=['Graduate (0)', 'Dropout (1)'])
plt.title(f"Confusion Matrix - Model Terbaik")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

#buat evaluasi akurasi untuk data train
y_pred_train = best_rf_model.predict(X_train)
print(f"Akurasi: {accuracy_score(y_train, y_pred_train) * 100:.2f}%")

#buat Classification Report untuk data train
print("\nClassification Report:")
print(classification_report(y_train, y_pred_train, target_names=['Graduate (0)', 'Dropout (1)']))

#buat confusion matrix untuk data train
cm_train = confusion_matrix(y_train, y_pred_train)

sns.heatmap(cm_train, annot=True, fmt="d",
            xticklabels=['Graduate (0)', 'Dropout (1)'],
            yticklabels=['Graduate (0)', 'Dropout (1)'])
plt.title(f"Confusion Matrix - Model Terbaik")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

#export model ke format joblib
joblib.dump(best_rf_model, 'model_rf.joblib')

!pip install sqlalchemy

!pip freeze > requirements.txt

"""#Testing"""

# File pipeline model yang sudah disimpan dari skrip sebelumnya
# Ganti nama file ini jika Anda menyimpannya dengan nama berbeda
model_filename = '/content/model_rf.joblib'

# File data mentah yang asli
data_filename = '/content/Dicoding/Belajar Penerapan Data Science/Tugas 2_Menyelesaikan Permasalahan Institusi Pendidikan/data.csv'

try:
    # Memuat seluruh pipeline (preprocessor + oversampler + model)
    model_pipeline = joblib.load(model_filename)
    print(f"Model pipeline '{model_filename}' berhasil dimuat.")
except FileNotFoundError:
    print(f"ERROR: File model '{model_filename}' tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip pelatihan sebelumnya dan menyimpan modelnya.")
    # Anda bisa menghentikan eksekusi di sini jika file tidak ada
    # model_pipeline = None
except Exception as e:
    print(f"Terjadi error saat memuat model: {e}")
    # model_pipeline = None

if 'model_pipeline' in locals():
    try:
        # Muat data mentah yang asli
        df_original = pd.read_csv(data_filename, delimiter=';')
        print(f"\nData asli '{data_filename}' berhasil dimuat.")

        # Saring untuk mendapatkan mahasiswa yang statusnya 'Enrolled'
        df_enrolled = df_original[df_original['Status'] == 'Enrolled'].copy()

        if df_enrolled.empty:
            print("Tidak ditemukan mahasiswa dengan status 'Enrolled' di data asli.")
        else:
            print(f"Ditemukan {df_enrolled.shape[0]} mahasiswa dengan status 'Enrolled'.")

    except FileNotFoundError:
        print(f"ERROR: File data '{data_filename}' tidak ditemukan.")
        df_enrolled = pd.DataFrame() # Buat dataframe kosong
    except Exception as e:
        print(f"Terjadi error saat memuat data: {e}")
        df_enrolled = pd.DataFrame() # Buat dataframe kosong

if not df_enrolled.empty:
    print("\nMemulai prediksi untuk mahasiswa 'Enrolled'...")

    # Dapatkan prediksi biner (0 = Graduate, 1 = Dropout)
    predictions_encoded = model_pipeline.predict(df_enrolled)

    # Dapatkan probabilitas prediksi
    # Kolom [0] = probabilitas Graduate
    # Kolom [1] = probabilitas Dropout
    predictions_proba = model_pipeline.predict_proba(df_enrolled)

    # Ambil probabilitas untuk kelas '1' (Dropout)
    probability_dropout = predictions_proba[:, 1]

    print("Prediksi selesai.")

    # Buat DataFrame hasil
    df_results = df_enrolled.copy()

    # Tambahkan kolom hasil prediksi
    df_results['Predicted_Status_Encoded'] = predictions_encoded
    df_results['Predicted_Status_Label'] = df_results['Predicted_Status_Encoded'].map({
        0: 'Diprediksi Graduate',
        1: 'Berisiko Dropout'
    })
    df_results['Probability_Dropout'] = probability_dropout

    print("\n--- Ringkasan Prediksi untuk Mahasiswa 'Enrolled' ---")
    print(df_results['Predicted_Status_Label'].value_counts())

    print("\n--- Contoh Hasil Prediksi ---")
    # Tampilkan beberapa kolom penting bersama hasil prediksi
    columns_to_show = [
        'Status', # Status asli (seharusnya semua 'Enrolled')
        'Predicted_Status_Label',
        'Probability_Dropout',
        'Age_at_enrollment',
        'Curricular_units_1st_sem_approved',
        'Curricular_units_1st_sem_grade',
        'Curricular_units_2nd_sem_approved',
        'Curricular_units_2nd_sem_grade'
    ]

    # Urutkan berdasarkan probabilitas dropout tertinggi
    df_results_sorted = df_results.sort_values(by='Probability_Dropout', ascending=False)

    print(df_results_sorted[columns_to_show].head(10))

    print("\nDataFrame 'df_results' kini berisi data mahasiswa 'Enrolled' beserta prediksi nasib mereka.")

output_filename = 'prediksi_risiko_dropout_mahasiswa_enrolled.csv'

try:
        # Menyimpan DataFrame yang sudah diurutkan ke file CSV
        # index=False agar nomor index pandas tidak ikut disimpan
  df_results_sorted.to_csv(output_filename, index=False)

  print(f"\nBerhasil! Hasil prediksi telah disimpan ke file: {output_filename}")

except Exception as e:
  print(f"\nTerjadi error saat menyimpan file CSV: {e}")

else:
    print("\nTidak ada data 'Enrolled' untuk diprediksi atau model tidak dimuat.")